### PR TITLE
Sentry

### PR DESCRIPTION
**Pull request by barbarahui**
This PR adds the sentry.io Django integration to the codebase. I followed these instructions: https://docs.sentry.io/platforms/python/integrations/django/

I was able to send a test 500 error from my local instance of public_interface to Sentry: https://california-digital-library.sentry.io/issues/5475120042/?project=4507346951274496 to verify that it works.

~~Right now, I've left the `traces_sample_rate` and `profiles_sample_rate` at 1.0, which means 100% profiling of sampled transactions (whatever that means, exactly). They recommend adjusting this for production. I figured we can try out Sentry on calisphere-stage and then adjust before deploying to prod?~~

I also added `sentry-sdk[django]` to `requirements.txt`.

~~When running `pip install -r requirements.txt` in a brand new venv, I found that I need to install boto3, magic, pillow and markdown as well. Not sure if there was some reason those were not added before? @amywieliczka I know there is some funkiness with exhibits requirements.txt vs public_interface requirements.txt.~~

### CODE REVIEW

**Comment by amywieliczka** [comment]
Hey @barbarahui - can you please remove those extra requirements? they're not actually used anywhere in this codebase - they're requirements of the exhibitapp: https://github.com/ucldc/exhibitapp/blob/main/requirements.txt and if you follow the README for getting setup (https://github.com/ucldc/public_interface?tab=readme-ov-file#install-python--django), you'll see it tells you to go install the exhibitapp requirements as well.

**Review by amywieliczka — CHANGES_REQUESTED** [review]
I don't think we want Sentry running on our local dev environments all the time. I also don't think we want it on calisphere-stage? We could wrap the initialization in a check that os.environ.get(UCLDC_DEBUG) is truthy, though.

**Comment by barbarahui** [comment]
@amywieliczka I agree that we probably only ever want sentry running on production. If that's the case though, then I'm thinking I should wrap the initialization in a check that:

```os.environ.get('UCLDC_FRONT') == 'https://calisphere.org/'```

rather than a check on DEBUG?

**Comment by bibliotechy** [comment]
@barbarahui @amywieliczka I actually think we do want it on Stage and Dev so we see exceptions happening before they get to production. But yeah, not in local dev envs.

**Comment by barbarahui** [comment]
@amywieliczka @bibliotechy I did some reading about `traces_sample_rate` and `profiles_sample_rate`:

`traces_sample_rate` - if set to 1.0, 100% of requests will be sampled. I figure we can use this to start and if it's too much, then we can turn it down.

`profiles_sample_rate` - "Sentry tracks your software's performance by sampling your program's call stack in a variety of environments. This feature collects function-level information about your code and enables you to fine-tune your program's performance. Sentry's profiler captures function calls and their exact locations, aggregates them, and shows you the most common code paths of your program. This highlights areas you could optimize to help increase both the performance of your code and increase user satisfaction, as well as drive down costs." I think it will be nice to get this info. I figure we don't need or want to sample 100% of calls to get a sense of the performance though, so I set it to 50% to start.

Let me know if that sounds reasonable. There are a fair number of other configuration options available, which we can delve into once we see what we're getting in sentry if we want to.

**Comment by barbarahui** [comment]
@amywieliczka @bibliotechy Update: based on a convo with publishing folks about what they're doing with Sentry for eScholarship, I adjusted the `traces_sample_rate` to 0.2. Apparently setting it higher caused performance issues.

I also removed profiling. We decided that if we need that information at some point, we can add it, but let's start simple.

**Comment by amywieliczka** [comment]
My thinking with UCLDC_DEBUG had been that if UCLDC_DEBUG is true, then we'll see the stack trace in the browser, and if UCLDC_DEBUG is unset, then we see a configured error page in the browser, and a trace in Sentry. 

If I understand correctly, though, we want to both see a stack trace in the browser AND get a trace in Sentry for calisphere-stage (and calisphere-test, if we ever spin that up). This makes sense - it would allow us to catch exceptions we might not /personally/ see in these deployed stage and dev environments. Since we want to get both for calisphere-stage, the setup here wouldn't work. 

I like how Hardy's example shows `environment="development"` and `release=str(janeway_version) + '-' + str(branch) + '-' + str(commit_hash)` as arguments to `sentry_sdk.init()`

I don't believe we currently ship our whole git repo to the beanstalks, but we could add it to our CodeBuild project - then we could determine a release of sorts. I'm not quite as sure about environment, though. 

At risk of adding another environment variable, what about something like "EB_ENVIRONMENT_NAME" - you could set it in the post-deploy and post-config hooks even? `export EB_ENVIRONMENT_NAME=$(/opt/elasticbeanstalk/bin/get-config container | jq .environment_name)`?

**Comment by barbarahui** [comment]
@amywieliczka Good idea! Your `jq` command works a treat when I'm logged onto one of the ec2 app servers. I'm also able to get the app version from `/opt/elasticbeanstalk/deployment/app_version_manifest.json`. For example, on the current stage machine:

```
$ export APP_VERSION=$(jq '.RuntimeSources."eb-calisphere" | keys[0]' /opt/elasticbeanstalk/deployment/app_version_manifest.json)
$ echo $APP_VERSION
"2024-06-11-284c2bb-exhibitapp-c956592"
```

**Review by amywieliczka — APPROVED** [review]

**Pull request merged**
